### PR TITLE
(bug) (types) Workaround for `mas account` failing on macOS >= 12

### PR DESCRIPTION
**Pull request by lucymhdavies**
Closes https://github.com/borksh/bork/issues/42

### CODE REVIEW

**Comment by skylarmacdonald** [comment]
Hmm, not sure why Danger is failing… but I think you probably know what she would have asked for 😉
Screenshot 2022-03-25 at 16 09 41

**Comment by lucymhdavies** [comment]
That is a good point 😂

I'll add something in here:
https://github.com/borksh/bork/blob/main/test/type-mas.bats#L6-L11

Looks like a simple thing to add

**Comment by lucymhdavies** [comment]
Huh.

Well okay then 😂 

```
not ok 218 mas status: returns FAILED_PRECONDITION when logged out
# (in test file test/type-mas.bats, line 22)
#   `[ "$status" -eq $STATUS_FAILED_PRECONDITION ]' failed
ok 219 mas status: does not return FAILED_PRECONDITION when mas account fails on macOS >= 12
```

**Comment by skylarmacdonald** [comment]
I think you will probably need to mock `uname -r` to fail in the test that is supposed to throw `$STATUS_FAILED_PRECONDITION` to get that one to pass.

**Comment by skylarmacdonald** [comment]
I think it is to do with your less than/greater than code — I don't think Bash is clever enough to do it like that when it isn't a pure integer.

Maybe try this:

```bash
if [ "$?" -gt 0 ]; then
  release=$(get_baking_platform_release)
  str_matches "$release" "^21\." || return $STATUS_FAILED_PRECONDITION
fi
```

**Comment by lucymhdavies** [comment]
Yeah, that could be it.

I was doing the following to check

```
$ [[ "21.3" < "21." ]] && echo TRUE || echo FALSE
FALSE

$ [[ "20.0" < "21." ]] && echo TRUE || echo FALSE
TRUE
```

**Review by skylarmacdonald — APPROVED** [review]

**Comment by skylarmacdonald** [comment]
That'll do nicely! Thanks very much.

**Pull request merged**
