### PR TITLE
Permanently skip `mas account` check

### PR DESCRIPTION
**Pull request by lucymhdavies**
Given https://github.com/borksh/bork/issues/42 's root cause issue shows no sign of being addressed, just don't run `mas account` anymore

Then I'm implementing https://github.com/borksh/bork/pull/49#issuecomment-1921793529

### CODE REVIEW

**Comment by lucymhdavies** [comment]
Looking into the failed Checks...


```
not ok 230 mas status: returns FAILED_PRECONDITION when logged out
# (in test file test/type-mas.bats, line 23)
#   `[ "$status" -eq $STATUS_FAILED_PRECONDITION ]' failed
```

Yeah, that makes sense. I'll have to remove that test too.

**Comment by lucymhdavies** [comment]
Well... now this is a weird one, that wasn't broken before...

```
not ok 170 file compile: echoes base64 representation to screen
# (in test file test/type-file.bats, line 122)
#   `expected="borkfiles__UmVhZG1lLm1kCg=\"$(base64 Readme.md)\""' failed with status 64
# base64: invalid argument Readme.md
# Usage:	base64 [-Ddh] [-b num] [-i in_file] [-o out_file]
#   -b, --break    break encoded string into num character lines
#   -Dd, --decode   decodes input
#   -h, --help     display this message
#   -i, --input    input file (default: "-" for stdin)
#   -o, --output   output file (default: "-" for stdout)
ok 171 file compile: outputs warning to stderr on missing file
not ok 172 file status: if compiled, uses stored variable
# (in test file test/type-file.bats, line 142)
#   `borkfiles__cGF0aC9mcm9tL3NvdXJjZQo="$(base64 Readme.md)"' failed with status 64
# base64: invalid argument Readme.md
# Usage:	base64 [-Ddh] [-b num] [-i in_file] [-o out_file]
#   -b, --break    break encoded string into num character lines
#   -Dd, --decode   decodes input
#   -h, --help     display this message
#   -i, --input    input file (default: "-" for stdin)
#   -o, --output   output file (default: "-" for stdout)
not ok 173 file install: if compiled, uses stored variable
# (in test file test/type-file.bats, line 150)
#   `borkfiles__cGF0aC9mcm9tL3NvdXJjZQo="$(base64 Readme.md)"' failed with status 64
# base64: invalid argument Readme.md
# Usage:	base64 [-Ddh] [-b num] [-i in_file] [-o out_file]
#   -b, --break    break encoded string into num character lines
#   -Dd, --decode   decodes input
#   -h, --help     display this message
#   -i, --input    input file (default: "-" for stdin)
#   -o, --output   output file (default: "-" for stdout)
```


That one didn't fail on the previous run, on a similar macOS version
https://github.com/borksh/bork/actions/runs/12126958117/job/33810162265

```
$ bats --tap test/
```
fails on my machine also, and in the same way

**Comment by lucymhdavies** [comment]
ah, it's one of _those_ tests. one of those "how did this ever work?!" kind of tests.

Because indeed, `base64 Readme.md` fails on macOS, because on macOS we need to do `base64 -i Readme.md`

Whereas the linux version... https://linux.die.net/man/1/base64 just takes the filename.


(the answer to how it ever worked is probably that the GitHub Runner now runs a newer macOS version than it did 11 months ago, and previously it somehow had linux-flavor base64)

Thankfully, `cat Readme.md | base64` should work in both

**Comment by skylarmacdonald** [comment]
LGTM! Thanks for taking this on.

**Pull request merged**
